name: CMake

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the `callbacks` library
      uses: actions/checkout@v3

    - name: Checkout the `simple-unit-tests` library
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/simple-unit-tests
        path: ./libraries/simple-unit-tests

    - name: Checkout the `containers` library
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/containers
        path: ./libraries/containers

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose

